# Generated by Django 5.1 on 2024-08-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
