# Generated by Django 5.1 on 2024-08-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('birthDay', models.DateField()),
                ('city', models.CharField(max_length=100)),
                ('telephon', models.CharField(max_length=15)),
                ('vacant', models.BooleanField(default=True)),
                ('subjectSign', models.CharField(max_length=100)),
                ('nextCours', models.CharField(max_length=200)),
                ('topicNextMeeting', models.CharField(max_length=200)),
            ],
        ),
    ]
